-- Active: 1747452264192@@127.0.0.1@3306@tarea2
-- Active: 1747350069595@@127.0.0.1@3306@tarea2
-- MySQL Script generated by MySQL Workbench
-- Mon Apr 21 21:54:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema tarea2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tarea2` ;

-- -----------------------------------------------------
-- Schema tarea2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tarea2` DEFAULT CHARACTER SET utf8 ;

GRANT ALL ON tarea2.* TO cc5002@localhost;

USE `tarea2` ;

-- -----------------------------------------------------
-- Table `tarea2`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`comuna` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comuna_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_comuna_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `tarea2`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comuna_id` INT NOT NULL,
  `sector` VARCHAR(100) NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(15) NULL,
  `dia_hora_inicio` DATETIME NOT NULL,
  `dia_hora_termino` DATETIME NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actividad_comuna1_idx` (`comuna_id` ASC),
  CONSTRAINT `fk_actividad_comuna1`
    FOREIGN KEY (`comuna_id`)
    REFERENCES `tarea2`.`comuna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruta_archivo` VARCHAR(300) NOT NULL,
  `nombre_archivo` VARCHAR(300) NOT NULL,
  `actividad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `actividad_id`),
  INDEX `fk_foto_actividad1_idx` (`actividad_id` ASC),
  CONSTRAINT `fk_foto_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `tarea2`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`contactar_por`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`contactar_por` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('whatsapp', 'telegram', 'X', 'instagram', 'tiktok', 'otra') NOT NULL,
  `identificador` VARCHAR(150) NOT NULL,
  `actividad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `actividad_id`),
  INDEX `fk_contactar_por_actividad1_idx` (`actividad_id` ASC),
  CONSTRAINT `fk_contactar_por_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `tarea2`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`actividad_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`actividad_tema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tema` ENUM('música', 'deporte', 'ciencias', 'religión', 'política', 'tecnología', 'juegos', 'baile', 'comida', 'otro') NOT NULL,
  `glosa_otro` VARCHAR(15) NULL,
  `actividad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `actividad_id`),
  INDEX `fk_actividad_tema_actividad1_idx` (`actividad_id` ASC),
  CONSTRAINT `fk_actividad_tema_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `tarea2`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ACTIVIDADES
INSERT INTO actividad (id, comuna_id, sector, nombre, email, celular, dia_hora_inicio, dia_hora_termino, descripcion)
VALUES
(1, 130208, 'Beauchef 850, terraza', 'Myke Tyson', 'boxeo@email.com', '912345678', '2025-03-28 12:00', '2025-03-28 14:00', 'Escuela de boxeo'),
(2, 130210, 'Plaza', 'Frutícola Don Pepe', 'fruta@email.com', '923456789', '2025-03-29 19:00', '2025-03-29 20:00', 'Cómo deshidratar fruta'),
(3, 130208, 'Parque O\'hhigins', 'Duki', 'musica@email.com', NULL, '2022-03-30 18:00', NULL, 'Música urbana'),
(4, 130207, 'Costanera Center', 'Faker', 'gaming@email.com', '934567890', '2025-04-01 19:00', '2025-04-01 21:00', 'Competencia de Gaming'),
(5, 130208, 'Beaucef 851, piso -1', 'Juan', 'programacion@email.com', NULL, '2025-04-10 16:00', '2025-04-10 18:00', 'Programación para jóvenes.');

-- FOTOS
INSERT INTO foto (id, ruta_archivo, nombre_archivo, actividad_id)
VALUES
(1, 'img/boxeo.png', 'boxeo.png', 1),
(2, 'img/frutas.jpg', 'frutas.jpg', 2),
(3, 'img/musica.png', 'musica.png', 3),
(4, 'img/gaming.png', 'gaming.png', 4),
(5, 'img/programacion.jpg', 'programacion.jpg', 5);


-- TEMAS
INSERT INTO actividad_tema (id, tema, glosa_otro, actividad_id)
VALUES
(1, 'deporte', NULL, 1),
(2, 'comida', NULL, 2),
(3, 'música', NULL, 3),
(4, 'juegos', NULL, 4),
(5, 'tecnología', NULL, 5);

